sonar.projectKey=jest-reactjs
sonar.projectName=jest-reactjs
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.inclusions=src/**/*.ts,src/**/*.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/setupTests.ts,src/main.tsx,node_modules/**,dist/**,coverage/**
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.host.url=http://localhost:9000
# Pass token via env: 
SONAR_TOKEN=sqp_88e38aa57fa4fe8a747aaa9969289e6c244d5a8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.testExecutionReportPaths=coverage/test-reporter.xml
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8



sonar-scanner 
  -Dsonar.projectKey=asfasdfasfa 
  -Dsonar.sources=. 
  -Dsonar.host.url=https://fuzzy-waffle-rrqxpvqpgr62pxw7-9000.app.github.dev 
  -Dsonar.token=sqp_c47ee3b985c9a8994ce9aaa8d597aa79ec77b4e3
  